### ISSUE TITLE
Provide a description for each value that can be set

### ISSUE THREAD

**Issue by imgios** [fonzdm/servarr#12]
### Description

Would be good to document all the values that can be set during the Helm Chart installation/update to customize it based on the user needs.

### Solution you'd like

I think we can do it in several ways, and they are all good options at the end. Those are the ones I was thinking about:

- Listing them in the [`README.md`](https://github.com/fonzdm/servarr/blob/main/README.md#values), but this would lead to a very long README and I don't like it so much;
- Creating a new markdown file maybe in `/docs` (we should then add this path to the [`.helmignore`](https://github.com/fonzdm/servarr/blob/main/.helmignore)) which will contains all the values with a short description, default value and an example.

Please, feel free to propose any other solution.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fonzdm** [comment]
I got the importance of this issue, and I will work on it.
Let's try your second idea and let's see what comes up 😄

**Comment by fonzdm** [comment]
Exploring the possibility to use [this tool](https://github.com/norwoodj/helm-docs).
There should be also an integration with `pre-commit hooks`, in order to automatically update docs for each helm modification.
Let's see...

**Comment by fonzdm** [comment]
Did some tweaks using the tool, this is the [first auto-generated README.md](https://github.com/fonzdm/servarr/blob/docs/values-description/servarr/README.md) file for the chart.
Setup the workflow actions to use. 
I will remove the `needs-triage` label and stark working on the proper documentation.

**Comment by fonzdm** [comment]
Let's be spicy and use:

> git-push-user-name: "Servarr Bot 🤖"

as suggested by @imgios  😄

**Comment by imgios** [comment]
> Did some tweaks using the tool, this is the [first auto-generated README.md](https://github.com/fonzdm/servarr/blob/docs/values-description/servarr/README.md) file for the chart. Setup the workflow actions to use. I will remove the `needs-triage` label and stark working on the proper documentation.

It looks really good to me. We just have to commment the parameters in the `values.yaml` like the following ones:

https://github.com/fonzdm/servarr/blob/a4f8e58da7d7f56e7c736eba1ceb70ae59db34b8/servarr/values.yaml#L1-L7

(but with a single hash `#` I guess)

**Comment by fonzdm** [comment]
Working on the issue, @imgios please can you take a look at [this Reame](https://github.com/fonzdm/servarr/tree/docs/values-description/servarr)?
I am removing all the complex sections for the various services.. I have something in mind, but it will need another PR 😛 
In fact, I think 99% of the services configuration is static, because it is a configuration of the subcharts that must not be modified by end users.. so I would like to only set anchors for the `ingress class` and `fqdn` of the services and stop there.

**Comment by imgios** [comment]
> Working on the issue, @imgios please can you take a look at [this Reame]

It looks really promising! I like the idea to have the values split into different sections, nice one!

> I am removing all the complex sections for the various services.. I have something in mind, but it will need another PR 😛

What are you thinking about? 👀 

> I think 99% of the services configuration is static, because it is a configuration of the subcharts that must not be modified by end users.. so I would like to only set anchors for the `ingress class` and `fqdn` of the services and stop there.

This sounds good, we can avoid to "expose" those static config to the user if it cannot be changed, otherwise people will only get confused.
