### ISSUE TITLE
Make the ingressClassName optional

### ISSUE THREAD

**Issue by imgios** [fonzdm/servarr#29]
### Description

I think that by default the ingress class name should be empty, because nginx is not the only one, and could be that the user is using something else (e.g. Traefik).

### Solution you'd like

https://github.com/fonzdm/servarr/blob/8a0aa86a082fb902d8c6c5bda303527ed9cafde8/values.yaml#L417

Comment out each `IngressClassName` parameter from the values.yaml

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fonzdm** [comment]
Yeah, that's true! Another thing that went under the hoods...
Do you suggest removing it completely or following the same principle as `storageClass` (using a global value, with an anchor?)

**Comment by imgios** [comment]
I think we can comment it out, in this way end users will know how to set it up correctly if they want to use a different ingress class, otherwise the deployment will use the default ingress class.

**Comment by imgios** [comment]
I haven't found anything about the pros and cons of using anchors within Helm Chart values, but I'll start working on it. If we decide to get rid of anchors, we may be able to adapt it in later stages.

**Comment by fonzdm** [comment]
Closed with #31
