### ISSUE TITLE
publish pipeline to push the Helm Chart to an external repository

### ISSUE THREAD

**Issue by imgios** [fonzdm/servarr#8]
### Description

Would be good to have a pipeline useful to push each Helm Chart release to an external repository.

### Solution you'd like

GitHub pipeline that executes a given set of commands to build the package and push it to an external repository for each commit (e.g. merge a PRs) done on `main` branch, taking the Chart version from the Chart.yaml:

https://github.com/fonzdm/servarr/blob/42e1a7ac26e5f1ff60af1a8c4f757d9fff781e7b/Chart.yaml#L5

**Comment by fonzdm** [comment]
Mmh, @imgios, I was thinking about are devops master @lucaam  for this... 👀

**Comment by lucaam** [comment]
> Mmh, @imgios, I was thinking about are devops master @lucaam for this... 👀

Challenge accepted  ✅

**Comment by imgios** [comment]
Hi @fonzdm / @lucaam,
I think there is a major questions to address before starting with the implementation:

> Where do we want to publish the Helm Chart?

I think that we can leverage on [ArtifactHub](https://artifacthub.io/) (tldr: the official Helm Repository) to spread the Chart around and make it easily accessible. This can also increase the chance of it getting found from new user. Moreover, we can also leverage to the GitHub Pages to make a "backup" or secondary repository.

In details, my proposal is to have one publish pipeline that is triggered for each commit on the `main` branch, composed of two jobs:

- `publish-artifacthub` will be responsible to publish the Helm Chart on ArtifactHub
- `publish-pages` will be responsible to:
  - Take the Chart from the `main` branch
  - Move it in a subdirectory named `charts`
  - Add an `index.yml` file in the root
  - (optional) Add the `robots.txt`
  - Deploy the new structure directly on GitHub Pages without using any additional branch

This solution let us leverage on both GitHub Pages and ArtifactHub, and ease us from managing additional branches.

What do you think?

**Comment by imgios** [comment]
Done in #35
